version: '3.8'

services:
  db:
    image: postgres:13
    container_name: api-6sem-db
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: api-6sem
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usuario -d api-6sem"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:7-alpine
    container_name: api-6sem-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  postgres_data:
  redis_data:
